# Generated by Django 5.0.1 on 2024-06-24 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackpackMate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name="Temple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("architecture", models.CharField(max_length=600)),
                ("major_high", models.CharField(max_length=600)),
                ("venue_img", models.ImageField(upload_to="images/")),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="district",
                        to="BackpackMate.district",
                    ),
                ),
            ],
        ),
    ]
