# Generated by Django 5.0.1 on 2024-06-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackpackMate", "0002_district_temple"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temple",
            name="architecture",
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name="temple",
            name="major_high",
            field=models.CharField(max_length=1200),
        ),
    ]
