# Generated by Django 5.0.1 on 2024-06-24 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackpackMate", "0003_alter_temple_architecture_alter_temple_major_high"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="saved",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="saved_districts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="temple",
            name="bookmark",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="saved_temples",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
