# Generated by Django 5.0.1 on 2024-06-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackpackMate", "0004_district_saved_temple_bookmark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="district",
            name="saved",
        ),
        migrations.RemoveField(
            model_name="temple",
            name="bookmark",
        ),
        migrations.CreateModel(
            name="Heritage_centers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("venue_img", models.ImageField(upload_to="images/")),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heritage_district",
                        to="BackpackMate.district",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tourist_spots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("venue_img", models.ImageField(upload_to="images/")),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tourist_spots_district",
                        to="BackpackMate.district",
                    ),
                ),
            ],
        ),
    ]
