# Generated by Django 5.0.1 on 2024-06-25 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackpackMate", "0006_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tourism_place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("venue_img", models.ImageField(upload_to="images/")),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tourist_place_district",
                        to="BackpackMate.district",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Tourist_spots",
        ),
    ]
