# Generated by Django 5.0.1 on 2024-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackpackMate", "0010_temple_mapurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temple",
            name="mapUrl",
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
