# Generated by Django 5.0.1 on 2024-12-20 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BackpackMate", "0013_comment_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="timestamp",
        ),
    ]
